### PR TITLE
Update recipe to v1.2.2

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by ericdill** [comment]
This feedstock probably needs to be regenerated. You can do that by installing conda-smithy from conda-forge (`conda install -c conda-forge conda-smithy`) and then running `conda-smithy rerender` from within the feedstock.  Could you try that and push those changes to this PR to see if that fixes the build failures?

**Comment by ericdill** [comment]
Well nevermind on my last comment!  I see #2

**Comment by synapticarbors** [comment]
@ericdill I'm guessing the circleci issue is caused by needing to re-render. I just made a separate pull request. But then appveyor is failing due to test suite issue.

**Comment by ericdill** [comment]
> But then appveyor is failing due to test suite issue.

We should just remove this:

```yaml
  requires:
    - setuptools
  commands:
    - cd {{ environ.SRC_DIR }} && python setup.py test
```

from the test section of the meta.yaml.  conda-forge should not be a platform where we also run the tests.  That's upstream's job!  (granted this is my fault for including that bit in the meta.yaml initially...)

**Comment by synapticarbors** [comment]
Ok, when the re-render finishes and is merged, I'll delete the that section of the tests before I re-push.

**Comment by synapticarbors** [comment]
@ericdill The build finally finished (Travis took 3 hours or so) and everything passed. If you could please review this at your earliest convenience, I'd appreciate it.

**Comment by ericdill** [comment]
LGTM thanks

**Pull request merged**
