### PR TITLE
Add backports.zoneinfo for Python < 3.9.

### PR DESCRIPTION
**Pull request by jtilly**
Version 3.0 depends on backports.zoneinfo for Python < 3.9, see [here](https://github.com/regebro/tzlocal/blob/14d5211bfb86d50eea390c826e90c326cb42135e/setup.cfg#L31).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~[ ] Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* ~[ ] Ensured the license file is being packaged.~

### CODE REVIEW

**Comment by synapticarbors** [comment]
@jtilly -- Sorry I missed that in the `setup.cfg` when I looked yesterday and thank you for putting in the fix. 

Do we need a `skip: True  #[py<36]` in the `build` section?

Also I don't understand the PR you submitted in the patches repo since I've never had to deal with that before. Can you explain what that's doing?

**Comment by jtilly** [comment]
> Do we need a skip: True #[py<36] in the build section?

I don't think we need it, because conda-forge isn't building packages for python<3.6 anymore. Anyways, I added it to be on the safe side.

> Also I don't understand the PR you submitted in the patches repo since I've never had to deal with that before. Can you explain what that's doing?

The point of that PR is to patch the dependencies of [this build](https://anaconda.org/conda-forge/tzlocal/3.0/download/noarch/tzlocal-3.0-pyhd8ed1ab_0.tar.bz2) (that's what you get when you do `conda install tzlocal` right now) so that it requires `python>=3.9` and users don't end up with a broken package their environments.

Once this PR here is merged, we're building the new version of `3.0` that will work for older Python versions as well (and because it doesn't contain `python >=3.6` as dependency, it won't be patched).

**Comment by jtilly** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
Can this be merged in please?

**Comment by tschoonj** [comment]
Thanks!

**Pull request merged**
