### PR TITLE
Re-render the feedstock

### PR DESCRIPTION
**Pull request by synapticarbors**
I was having problems with #1 so to partially solve those issues, I'm attempting to re-render the feedstock.

### CODE REVIEW

**Comment by jjhelmus** [comment]
Looks good. You should be able to apply the changes from #1 on top of this and be good to go.

**Comment by synapticarbors** [comment]
All checks have passed on the re-render. Please merge this PR at your earliest convenience. Then I can pull in upstream on #1

**Comment by jjhelmus** [comment]
You can just add the changes in #1 to this PR is you want instead of making a separate PR.  Unfortunately I do not have merge permissions on this repository.

**Comment by jjhelmus** [comment]
I believe @ericdill has merged rights and should be able to review.

**Pull request merged**
